# Use an official Node runtime as a parent image
FROM node:14-alpine

# Set the working directory to /app
COPY /suprajaramak /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the app source code to the container
COPY . .

# Build the app
RUN npm run build

# Install serve to run the built app

# Copy the rest of the application code to the container
COPY . .

# Build the application
RUN npm run build

# Set the command to start the application
CMD ["npm", "start"]docker
