# Use an official Node runtime as a parent image
FROM node:14-alpine

# Set the working directory to /app
COPY /suprajaramak /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the app source code to the container
COPY . .

# Build the app
RUN npm run build

# Install serve to run the built app
RUN npm install -g serve

# Expose port 80
EXPOSE 80

# Run the app
CMD ["serve", "-s", "build"]
